

const pos_ar={'N': 'اسم',
     'PN': 'اسم علم',
     'ADJ': 'صفة',
     'IMPN': 'اسم فعل أمر',
     'PRON': 'ضمير',
     'DEM': 'اسم اشارة',
     'REL': 'اسم موصول',
     'T': 'ظرف زمان',
     'LOC': 'ظرف مكان',
     'V': 'فعل',
     'P': 'حرف جر',
     'EMPH': 'لام التوكيد',
     'IMPV': 'لام الامر',
     'PRP': 'لام التعليل',
     'CONJ': 'حرف عطف',
     'SUB': 'حرف مصدري',
     'ACC': 'حرف نصب',
     'AMD': 'حرف استدراك',
     'ANS': 'حرف جواب',
     'AVR': 'حرف ردع',
     'CAUS': 'حرف سببية',
     'CERT': 'حرف تحقيق',
     'CIRC': 'حرف حال',
     'COM': 'واو المعية',
     'COND': 'حرف شرط',
     'EQ': 'حرف تسوية',
     'EXH': 'حرف تحضيض',
     'EXL': 'حرف تفصيل',
     'EXP': 'أداة استثناء',
     'FUT': 'حرف استقبال',
     'INC': 'حرف ابتداء',
     'INT': 'حرف تفسير',
     'INTG': 'حرف استفهام',
     'NEG': 'حرف نفي',
     'PREV': 'حرف كاف',
     'PRO': 'حرف نهي',
     'REM': 'حرف استئنافية',
     'RES': 'أداة حصر',
     'RET': 'حرف اضراب',
     'RSLT': 'حرف واقع في جواب الشرط',
     'SUP': 'حرف زائد',
     'SUR': 'حرف فجاءة',
     'VOC': 'حرف نداء',
     'INL': 'حروف مقطعة',
     'DET': 'ال التعريف',
      '_': '_'};
const pos_en={'N':'Noun',
     'PN':'Proper noun',
     'ADJ':'Adjective',
     'IMPN':'Imperative verbal noun',
     'PRON':'Personal pronoun',
     'DEM':'Demonstrative pronoun',
     'REL':'Relative pronoun',
     'T':'Time adverb',
     'LOC':'Location adverb',
     'V':'Verb',
     'P':'Preposition',
     'EMPH':'Emphatic lām prefix',
     'IMPV':'Imperative lām prefix',
     'PRP':'Purpose lām prefix',
     'CONJ':'Coordinating conjunction',
     'SUB':'Subordinating conjunction',
     'ACC':'Accusative particle',
     'AMD':'Amendment particle',
     'ANS':'Answer particle',
     'AVR':'Aversion particle',
     'CAUS':'Particle of cause',
     'CERT':'Particle of certainty',
     'CIRC':'Circumstantial particle',
     'COM':'Comitative particle',
     'COND':'Conditional particle',
     'EQ':'Equalization particle',
     'EXH':'Exhortation particle',
     'EXL':'Explanation particle',
     'EXP':'Exceptive particle',
     'FUT':'Future particle',
     'INC':'Inceptive particle',
     'INT':'Particle of interpretation',
     'INTG':'Interogative particle',
     'NEG':'Negative particle',
     'PREV':'Preventive particle',
     'PRO':'Prohibition particle',
     'REM':'Resumption particle',
     'RES':'Restriction particle',
     'RET':'Retraction particle',
     'RSLT':'Result particle',
     'SUP':'Supplemental particle',
     'SUR':'Surprise particle',
     'VOC':'Vocative particle',
     'INL':'Quranic initials',
     'DET':'Determiner',
      '_': '_'};

const Verb_form_ar={'(I)'   : 'فَعَلَ',
               '(II)'  : 'فَعَّلَ',
               '(III)' : 'فَاعَلَ',
               '(IV)'  : 'أَفْعَلَ',
               '(IX)'  : 'إِفْعَلَّ',
               '(V)'   : 'تَفَعَّلَ',
               '(VI)'  : 'تَفَاعَلَ',
               '(VII)' : 'إِنْفَعَلَ',
               '(VIII)': 'إِفْتَعَلَ',
               '(X)'   : 'إِسْتَفْعَلَ',
               '(XI)'  : 'فَعْلَلَ',
               '(XII)' : 'تَفَعْلَلَ',
               '_' : '_'};
const Verb_form_en={'(I)': '/faʕala/',
             '(II)': '/faʕʕala/',
             '(III)': '/faʕala/',
             '(IV)': '/ʔafʕala/',
             '(IX)': '/ʔifʕalla/',
             '(V)': '/tafaʕʕala/',
             '(VI)': '/tafaaʕala/',
             '(VII)': '/ʔinfaʕala/',
             '(VIII)': '/ʔiftaʕala/',
             '(X)': '/ʔistafʕala/',
             '(XI)': '/faʕlala/',
             '(XII)': '/tafaʕlala/',
             '_': '_'};
const verb_time_ar= {'PERF': 'فعل ماضي',
             'IMPF': 'فعل مضارع',
             'IMPV': 'فعل أمر',
             '_' : '_'};
const verb_time_en= {'PERF': 'Perfect verb',
               'IMPF': 'Imperfect verb',
               'IMPV': 'Imperative verb',
               '_' : '_'};
const verb_mood_ar= {'MOOD:IND': 'مرفوع',
              'MOOD:JUS': 'مجزوم',
              'MOOD:SUBJ': 'منصوب',
              '_' : '_'};
const verb_mood_en= {'MOOD:IND': 'Indicative mood',
              'MOOD:JUS': 'Subjunctive mood',
              'MOOD:SUBJ': 'Jussive mood',
              '_' : '_'};
const verb_voice_ar={'ACT': 'مبني للمعلوم',
               'PASS': 'مبني للمجهول',
                '_':'_'};
const verb_voice_en={'ACT': 'Active voice',
               'PASS': 'Passive voice',
                '_':'_'};

const nominal_state_ar={'DEF'  : 'معرفة',
                  'INDEF': 'نكرة',
                  '_':'_'};
const nominal_state_en={'DEF'  : 'Definite state',
                  'INDEF': 'Indefinite state',
                  '_':'_'};

const nominal_case_ar ={'NOM': 'مرفوع',
                  'ACC': 'منصوب',
                  'GEN': 'مجرور',
                  '_' : '_'};
const nominal_case_en ={'NOM': 'Nominative case',
                  'ACC': 'Accusative case',
                  'GEN': 'Genitive case',
                  '_' : '_'};
const derived_noun_ar ={'ACT_PCPL':'اسم فاعل',
                  'PASS_PCPL':'اسم مفعول',
                  'VN':'مصدر',
                  '_':'_'};
const derived_noun_en ={'ACT_PCPL':'Active participle',
                  'PASS_PCPL':'Passive participle',
                  'VN':'Verbal noun',
                  '_':'_'};
const special_group_ar ={'SP:<in~': 'ان واخواتها',
                   'SP:kaAd': 'كاد واخواتها',
                   'SP:kaAn': 'كان واخواتها',
                   '_' : '_'};
const special_group_en ={'SP:<in~': 'inna wa akhowatuha (Emphasis)',
                   'SP:kaAd': 'kaada wa akhowatuha (Mood)',
                   'SP:kaAn': 'kaan wa akhowatuha (Tense)',
                   '_' : '_'};

const person_ar={'1': 'واحد',
            '2': 'اثنين',
            '3': 'ثلاثة',
            '_':'_'};
const person_en={'1': 'first person',
            '2': 'second person',
            '3': 'third person',
            '_':'_'};

const gender_ar ={'M': 'مذكر',
            'F': 'مؤنث',
            '_':'_'};
const gender_en ={'M': 'masculine',
            'F': 'feminine',
            '_':'_'};

const number_ar ={'S': 'مفرد',
            'D': 'مثنى',
            'P': 'جمع',
            '_':'_'};
const number_en ={'S': 'singular',
            'D': 'dual',
            'P': 'plural',
            '_':'_'};

const prefixs ={'A:EQ+': 'همزة تسوية',
         'A:INTG+': 'همزة استفهام',
         'Al+': 'ال التعريف',
         'bi+': 'باء الجر',
         'f:CAUS+': 'فاء السببية',
         'f:CONJ+': 'فاء العطف',
         'f:REM+': 'فاء الإستئناف',
         'f:RSLT+': 'فاء الشرط',
         'f:SUP+': 'فاء الزائدة',
         'ha+': 'هاء النداء',
         'ka+': 'كاف الجر',
         'l:EMPH+': 'لام التوكيد',
         'l:IMPV+': 'لام الأمر',
         'l:P+': 'لام الجر',
         'l:PRP+': 'لام التعليل',
         'sa+': 'سين المستقبل',
         'ta+': 'تاء النداء',
         'w:CIRC+': 'واو الظرفية',
         'w:COM+': 'واو المعية',
         'w:CONJ+': 'واو العطف',
         'w:P+': 'واو الجر',
         'w:REM+': 'واو الإستئناف',
         'w:SUP+': 'واو الزائدة',
         'ya+': 'ياء النداء',
         '_': '_'};
const suffixs={'VOC:m' : 'ميم النداء',
        'EMPH:n': 'نون التوكيد',
        'PRON': 'ضمير متصل',
        'l:P+': 'لام الجر',
        '_': '_'};